#ifndef GLS_EVENT_DISPATCH_HH_
#define GLS_EVENT_DISPATCH_HH_

#include <boost/signals2.hpp>

namespace gls {
template <typename Op>
using signal = boost::signals2::signal<Op>;
using connection = boost::signals2::connection;

struct event_dispatch {
  using quit_signal_t = signal<void()>;
  using quit_slot_t = quit_signal_t::slot_type;
  using keydown_unknown_signal_t = signal<void()>;
  using keydown_unknown_slot_t = keydown_unknown_signal_t::slot_type;
  using keydown_backspace_signal_t = signal<void()>;
  using keydown_backspace_slot_t = keydown_backspace_signal_t::slot_type;
  using keydown_tab_signal_t = signal<void()>;
  using keydown_tab_slot_t = keydown_tab_signal_t::slot_type;
  using keydown_return_signal_t = signal<void()>;
  using keydown_return_slot_t = keydown_return_signal_t::slot_type;
  using keydown_escape_signal_t = signal<void()>;
  using keydown_escape_slot_t = keydown_escape_signal_t::slot_type;
  using keydown_space_signal_t = signal<void()>;
  using keydown_space_slot_t = keydown_space_signal_t::slot_type;
  using keydown_exclaim_signal_t = signal<void()>;
  using keydown_exclaim_slot_t = keydown_exclaim_signal_t::slot_type;
  using keydown_quotedbl_signal_t = signal<void()>;
  using keydown_quotedbl_slot_t = keydown_quotedbl_signal_t::slot_type;
  using keydown_hash_signal_t = signal<void()>;
  using keydown_hash_slot_t = keydown_hash_signal_t::slot_type;
  using keydown_dollar_signal_t = signal<void()>;
  using keydown_dollar_slot_t = keydown_dollar_signal_t::slot_type;
  using keydown_percent_signal_t = signal<void()>;
  using keydown_percent_slot_t = keydown_percent_signal_t::slot_type;
  using keydown_ampersand_signal_t = signal<void()>;
  using keydown_ampersand_slot_t = keydown_ampersand_signal_t::slot_type;
  using keydown_quote_signal_t = signal<void()>;
  using keydown_quote_slot_t = keydown_quote_signal_t::slot_type;
  using keydown_leftparen_signal_t = signal<void()>;
  using keydown_leftparen_slot_t = keydown_leftparen_signal_t::slot_type;
  using keydown_rightparen_signal_t = signal<void()>;
  using keydown_rightparen_slot_t = keydown_rightparen_signal_t::slot_type;
  using keydown_asterisk_signal_t = signal<void()>;
  using keydown_asterisk_slot_t = keydown_asterisk_signal_t::slot_type;
  using keydown_plus_signal_t = signal<void()>;
  using keydown_plus_slot_t = keydown_plus_signal_t::slot_type;
  using keydown_comma_signal_t = signal<void()>;
  using keydown_comma_slot_t = keydown_comma_signal_t::slot_type;
  using keydown_minus_signal_t = signal<void()>;
  using keydown_minus_slot_t = keydown_minus_signal_t::slot_type;
  using keydown_period_signal_t = signal<void()>;
  using keydown_period_slot_t = keydown_period_signal_t::slot_type;
  using keydown_slash_signal_t = signal<void()>;
  using keydown_slash_slot_t = keydown_slash_signal_t::slot_type;
  using keydown_0_signal_t = signal<void()>;
  using keydown_0_slot_t = keydown_0_signal_t::slot_type;
  using keydown_1_signal_t = signal<void()>;
  using keydown_1_slot_t = keydown_1_signal_t::slot_type;
  using keydown_2_signal_t = signal<void()>;
  using keydown_2_slot_t = keydown_2_signal_t::slot_type;
  using keydown_3_signal_t = signal<void()>;
  using keydown_3_slot_t = keydown_3_signal_t::slot_type;
  using keydown_4_signal_t = signal<void()>;
  using keydown_4_slot_t = keydown_4_signal_t::slot_type;
  using keydown_5_signal_t = signal<void()>;
  using keydown_5_slot_t = keydown_5_signal_t::slot_type;
  using keydown_6_signal_t = signal<void()>;
  using keydown_6_slot_t = keydown_6_signal_t::slot_type;
  using keydown_7_signal_t = signal<void()>;
  using keydown_7_slot_t = keydown_7_signal_t::slot_type;
  using keydown_8_signal_t = signal<void()>;
  using keydown_8_slot_t = keydown_8_signal_t::slot_type;
  using keydown_9_signal_t = signal<void()>;
  using keydown_9_slot_t = keydown_9_signal_t::slot_type;
  using keydown_colon_signal_t = signal<void()>;
  using keydown_colon_slot_t = keydown_colon_signal_t::slot_type;
  using keydown_semicolon_signal_t = signal<void()>;
  using keydown_semicolon_slot_t = keydown_semicolon_signal_t::slot_type;
  using keydown_less_signal_t = signal<void()>;
  using keydown_less_slot_t = keydown_less_signal_t::slot_type;
  using keydown_equals_signal_t = signal<void()>;
  using keydown_equals_slot_t = keydown_equals_signal_t::slot_type;
  using keydown_greater_signal_t = signal<void()>;
  using keydown_greater_slot_t = keydown_greater_signal_t::slot_type;
  using keydown_question_signal_t = signal<void()>;
  using keydown_question_slot_t = keydown_question_signal_t::slot_type;
  using keydown_at_signal_t = signal<void()>;
  using keydown_at_slot_t = keydown_at_signal_t::slot_type;
  using keydown_leftbracket_signal_t = signal<void()>;
  using keydown_leftbracket_slot_t = keydown_leftbracket_signal_t::slot_type;
  using keydown_backslash_signal_t = signal<void()>;
  using keydown_backslash_slot_t = keydown_backslash_signal_t::slot_type;
  using keydown_rightbracket_signal_t = signal<void()>;
  using keydown_rightbracket_slot_t = keydown_rightbracket_signal_t::slot_type;
  using keydown_caret_signal_t = signal<void()>;
  using keydown_caret_slot_t = keydown_caret_signal_t::slot_type;
  using keydown_underscore_signal_t = signal<void()>;
  using keydown_underscore_slot_t = keydown_underscore_signal_t::slot_type;
  using keydown_backquote_signal_t = signal<void()>;
  using keydown_backquote_slot_t = keydown_backquote_signal_t::slot_type;
  using keydown_a_signal_t = signal<void()>;
  using keydown_a_slot_t = keydown_a_signal_t::slot_type;
  using keydown_b_signal_t = signal<void()>;
  using keydown_b_slot_t = keydown_b_signal_t::slot_type;
  using keydown_c_signal_t = signal<void()>;
  using keydown_c_slot_t = keydown_c_signal_t::slot_type;
  using keydown_d_signal_t = signal<void()>;
  using keydown_d_slot_t = keydown_d_signal_t::slot_type;
  using keydown_e_signal_t = signal<void()>;
  using keydown_e_slot_t = keydown_e_signal_t::slot_type;
  using keydown_f_signal_t = signal<void()>;
  using keydown_f_slot_t = keydown_f_signal_t::slot_type;
  using keydown_g_signal_t = signal<void()>;
  using keydown_g_slot_t = keydown_g_signal_t::slot_type;
  using keydown_h_signal_t = signal<void()>;
  using keydown_h_slot_t = keydown_h_signal_t::slot_type;
  using keydown_i_signal_t = signal<void()>;
  using keydown_i_slot_t = keydown_i_signal_t::slot_type;
  using keydown_j_signal_t = signal<void()>;
  using keydown_j_slot_t = keydown_j_signal_t::slot_type;
  using keydown_k_signal_t = signal<void()>;
  using keydown_k_slot_t = keydown_k_signal_t::slot_type;
  using keydown_l_signal_t = signal<void()>;
  using keydown_l_slot_t = keydown_l_signal_t::slot_type;
  using keydown_m_signal_t = signal<void()>;
  using keydown_m_slot_t = keydown_m_signal_t::slot_type;
  using keydown_n_signal_t = signal<void()>;
  using keydown_n_slot_t = keydown_n_signal_t::slot_type;
  using keydown_o_signal_t = signal<void()>;
  using keydown_o_slot_t = keydown_o_signal_t::slot_type;
  using keydown_p_signal_t = signal<void()>;
  using keydown_p_slot_t = keydown_p_signal_t::slot_type;
  using keydown_q_signal_t = signal<void()>;
  using keydown_q_slot_t = keydown_q_signal_t::slot_type;
  using keydown_r_signal_t = signal<void()>;
  using keydown_r_slot_t = keydown_r_signal_t::slot_type;
  using keydown_s_signal_t = signal<void()>;
  using keydown_s_slot_t = keydown_s_signal_t::slot_type;
  using keydown_t_signal_t = signal<void()>;
  using keydown_t_slot_t = keydown_t_signal_t::slot_type;
  using keydown_u_signal_t = signal<void()>;
  using keydown_u_slot_t = keydown_u_signal_t::slot_type;
  using keydown_v_signal_t = signal<void()>;
  using keydown_v_slot_t = keydown_v_signal_t::slot_type;
  using keydown_w_signal_t = signal<void()>;
  using keydown_w_slot_t = keydown_w_signal_t::slot_type;
  using keydown_x_signal_t = signal<void()>;
  using keydown_x_slot_t = keydown_x_signal_t::slot_type;
  using keydown_y_signal_t = signal<void()>;
  using keydown_y_slot_t = keydown_y_signal_t::slot_type;
  using keydown_z_signal_t = signal<void()>;
  using keydown_z_slot_t = keydown_z_signal_t::slot_type;
  using keydown_delete_signal_t = signal<void()>;
  using keydown_delete_slot_t = keydown_delete_signal_t::slot_type;
  using keydown_capslock_signal_t = signal<void()>;
  using keydown_capslock_slot_t = keydown_capslock_signal_t::slot_type;
  using keydown_f1_signal_t = signal<void()>;
  using keydown_f1_slot_t = keydown_f1_signal_t::slot_type;
  using keydown_f2_signal_t = signal<void()>;
  using keydown_f2_slot_t = keydown_f2_signal_t::slot_type;
  using keydown_f3_signal_t = signal<void()>;
  using keydown_f3_slot_t = keydown_f3_signal_t::slot_type;
  using keydown_f4_signal_t = signal<void()>;
  using keydown_f4_slot_t = keydown_f4_signal_t::slot_type;
  using keydown_f5_signal_t = signal<void()>;
  using keydown_f5_slot_t = keydown_f5_signal_t::slot_type;
  using keydown_f6_signal_t = signal<void()>;
  using keydown_f6_slot_t = keydown_f6_signal_t::slot_type;
  using keydown_f7_signal_t = signal<void()>;
  using keydown_f7_slot_t = keydown_f7_signal_t::slot_type;
  using keydown_f8_signal_t = signal<void()>;
  using keydown_f8_slot_t = keydown_f8_signal_t::slot_type;
  using keydown_f9_signal_t = signal<void()>;
  using keydown_f9_slot_t = keydown_f9_signal_t::slot_type;
  using keydown_f10_signal_t = signal<void()>;
  using keydown_f10_slot_t = keydown_f10_signal_t::slot_type;
  using keydown_f11_signal_t = signal<void()>;
  using keydown_f11_slot_t = keydown_f11_signal_t::slot_type;
  using keydown_f12_signal_t = signal<void()>;
  using keydown_f12_slot_t = keydown_f12_signal_t::slot_type;
  using keydown_printscreen_signal_t = signal<void()>;
  using keydown_printscreen_slot_t = keydown_printscreen_signal_t::slot_type;
  using keydown_scrolllock_signal_t = signal<void()>;
  using keydown_scrolllock_slot_t = keydown_scrolllock_signal_t::slot_type;
  using keydown_pause_signal_t = signal<void()>;
  using keydown_pause_slot_t = keydown_pause_signal_t::slot_type;
  using keydown_insert_signal_t = signal<void()>;
  using keydown_insert_slot_t = keydown_insert_signal_t::slot_type;
  using keydown_home_signal_t = signal<void()>;
  using keydown_home_slot_t = keydown_home_signal_t::slot_type;
  using keydown_pageup_signal_t = signal<void()>;
  using keydown_pageup_slot_t = keydown_pageup_signal_t::slot_type;
  using keydown_end_signal_t = signal<void()>;
  using keydown_end_slot_t = keydown_end_signal_t::slot_type;
  using keydown_pagedown_signal_t = signal<void()>;
  using keydown_pagedown_slot_t = keydown_pagedown_signal_t::slot_type;
  using keydown_right_signal_t = signal<void()>;
  using keydown_right_slot_t = keydown_right_signal_t::slot_type;
  using keydown_left_signal_t = signal<void()>;
  using keydown_left_slot_t = keydown_left_signal_t::slot_type;
  using keydown_down_signal_t = signal<void()>;
  using keydown_down_slot_t = keydown_down_signal_t::slot_type;
  using keydown_up_signal_t = signal<void()>;
  using keydown_up_slot_t = keydown_up_signal_t::slot_type;
  using keydown_numlockclear_signal_t = signal<void()>;
  using keydown_numlockclear_slot_t = keydown_numlockclear_signal_t::slot_type;
  using keydown_kp_divide_signal_t = signal<void()>;
  using keydown_kp_divide_slot_t = keydown_kp_divide_signal_t::slot_type;
  using keydown_kp_multiply_signal_t = signal<void()>;
  using keydown_kp_multiply_slot_t = keydown_kp_multiply_signal_t::slot_type;
  using keydown_kp_minus_signal_t = signal<void()>;
  using keydown_kp_minus_slot_t = keydown_kp_minus_signal_t::slot_type;
  using keydown_kp_plus_signal_t = signal<void()>;
  using keydown_kp_plus_slot_t = keydown_kp_plus_signal_t::slot_type;
  using keydown_kp_enter_signal_t = signal<void()>;
  using keydown_kp_enter_slot_t = keydown_kp_enter_signal_t::slot_type;
  using keydown_kp_1_signal_t = signal<void()>;
  using keydown_kp_1_slot_t = keydown_kp_1_signal_t::slot_type;
  using keydown_kp_2_signal_t = signal<void()>;
  using keydown_kp_2_slot_t = keydown_kp_2_signal_t::slot_type;
  using keydown_kp_3_signal_t = signal<void()>;
  using keydown_kp_3_slot_t = keydown_kp_3_signal_t::slot_type;
  using keydown_kp_4_signal_t = signal<void()>;
  using keydown_kp_4_slot_t = keydown_kp_4_signal_t::slot_type;
  using keydown_kp_5_signal_t = signal<void()>;
  using keydown_kp_5_slot_t = keydown_kp_5_signal_t::slot_type;
  using keydown_kp_6_signal_t = signal<void()>;
  using keydown_kp_6_slot_t = keydown_kp_6_signal_t::slot_type;
  using keydown_kp_7_signal_t = signal<void()>;
  using keydown_kp_7_slot_t = keydown_kp_7_signal_t::slot_type;
  using keydown_kp_8_signal_t = signal<void()>;
  using keydown_kp_8_slot_t = keydown_kp_8_signal_t::slot_type;
  using keydown_kp_9_signal_t = signal<void()>;
  using keydown_kp_9_slot_t = keydown_kp_9_signal_t::slot_type;
  using keydown_kp_0_signal_t = signal<void()>;
  using keydown_kp_0_slot_t = keydown_kp_0_signal_t::slot_type;
  using keydown_kp_period_signal_t = signal<void()>;
  using keydown_kp_period_slot_t = keydown_kp_period_signal_t::slot_type;
  using keydown_application_signal_t = signal<void()>;
  using keydown_application_slot_t = keydown_application_signal_t::slot_type;
  using keydown_power_signal_t = signal<void()>;
  using keydown_power_slot_t = keydown_power_signal_t::slot_type;
  using keydown_kp_equals_signal_t = signal<void()>;
  using keydown_kp_equals_slot_t = keydown_kp_equals_signal_t::slot_type;
  using keydown_f13_signal_t = signal<void()>;
  using keydown_f13_slot_t = keydown_f13_signal_t::slot_type;
  using keydown_f14_signal_t = signal<void()>;
  using keydown_f14_slot_t = keydown_f14_signal_t::slot_type;
  using keydown_f15_signal_t = signal<void()>;
  using keydown_f15_slot_t = keydown_f15_signal_t::slot_type;
  using keydown_f16_signal_t = signal<void()>;
  using keydown_f16_slot_t = keydown_f16_signal_t::slot_type;
  using keydown_f17_signal_t = signal<void()>;
  using keydown_f17_slot_t = keydown_f17_signal_t::slot_type;
  using keydown_f18_signal_t = signal<void()>;
  using keydown_f18_slot_t = keydown_f18_signal_t::slot_type;
  using keydown_f19_signal_t = signal<void()>;
  using keydown_f19_slot_t = keydown_f19_signal_t::slot_type;
  using keydown_f20_signal_t = signal<void()>;
  using keydown_f20_slot_t = keydown_f20_signal_t::slot_type;
  using keydown_f21_signal_t = signal<void()>;
  using keydown_f21_slot_t = keydown_f21_signal_t::slot_type;
  using keydown_f22_signal_t = signal<void()>;
  using keydown_f22_slot_t = keydown_f22_signal_t::slot_type;
  using keydown_f23_signal_t = signal<void()>;
  using keydown_f23_slot_t = keydown_f23_signal_t::slot_type;
  using keydown_f24_signal_t = signal<void()>;
  using keydown_f24_slot_t = keydown_f24_signal_t::slot_type;
  using keydown_execute_signal_t = signal<void()>;
  using keydown_execute_slot_t = keydown_execute_signal_t::slot_type;
  using keydown_help_signal_t = signal<void()>;
  using keydown_help_slot_t = keydown_help_signal_t::slot_type;
  using keydown_menu_signal_t = signal<void()>;
  using keydown_menu_slot_t = keydown_menu_signal_t::slot_type;
  using keydown_select_signal_t = signal<void()>;
  using keydown_select_slot_t = keydown_select_signal_t::slot_type;
  using keydown_stop_signal_t = signal<void()>;
  using keydown_stop_slot_t = keydown_stop_signal_t::slot_type;
  using keydown_again_signal_t = signal<void()>;
  using keydown_again_slot_t = keydown_again_signal_t::slot_type;
  using keydown_undo_signal_t = signal<void()>;
  using keydown_undo_slot_t = keydown_undo_signal_t::slot_type;
  using keydown_cut_signal_t = signal<void()>;
  using keydown_cut_slot_t = keydown_cut_signal_t::slot_type;
  using keydown_copy_signal_t = signal<void()>;
  using keydown_copy_slot_t = keydown_copy_signal_t::slot_type;
  using keydown_paste_signal_t = signal<void()>;
  using keydown_paste_slot_t = keydown_paste_signal_t::slot_type;
  using keydown_find_signal_t = signal<void()>;
  using keydown_find_slot_t = keydown_find_signal_t::slot_type;
  using keydown_mute_signal_t = signal<void()>;
  using keydown_mute_slot_t = keydown_mute_signal_t::slot_type;
  using keydown_volumeup_signal_t = signal<void()>;
  using keydown_volumeup_slot_t = keydown_volumeup_signal_t::slot_type;
  using keydown_volumedown_signal_t = signal<void()>;
  using keydown_volumedown_slot_t = keydown_volumedown_signal_t::slot_type;
  using keydown_kp_comma_signal_t = signal<void()>;
  using keydown_kp_comma_slot_t = keydown_kp_comma_signal_t::slot_type;
  using keydown_kp_equalsas400_signal_t = signal<void()>;
  using keydown_kp_equalsas400_slot_t
    = keydown_kp_equalsas400_signal_t::slot_type;
  using keydown_alterase_signal_t = signal<void()>;
  using keydown_alterase_slot_t = keydown_alterase_signal_t::slot_type;
  using keydown_sysreq_signal_t = signal<void()>;
  using keydown_sysreq_slot_t = keydown_sysreq_signal_t::slot_type;
  using keydown_cancel_signal_t = signal<void()>;
  using keydown_cancel_slot_t = keydown_cancel_signal_t::slot_type;
  using keydown_clear_signal_t = signal<void()>;
  using keydown_clear_slot_t = keydown_clear_signal_t::slot_type;
  using keydown_prior_signal_t = signal<void()>;
  using keydown_prior_slot_t = keydown_prior_signal_t::slot_type;
  using keydown_return2_signal_t = signal<void()>;
  using keydown_return2_slot_t = keydown_return2_signal_t::slot_type;
  using keydown_separator_signal_t = signal<void()>;
  using keydown_separator_slot_t = keydown_separator_signal_t::slot_type;
  using keydown_out_signal_t = signal<void()>;
  using keydown_out_slot_t = keydown_out_signal_t::slot_type;
  using keydown_oper_signal_t = signal<void()>;
  using keydown_oper_slot_t = keydown_oper_signal_t::slot_type;
  using keydown_clearagain_signal_t = signal<void()>;
  using keydown_clearagain_slot_t = keydown_clearagain_signal_t::slot_type;
  using keydown_crsel_signal_t = signal<void()>;
  using keydown_crsel_slot_t = keydown_crsel_signal_t::slot_type;
  using keydown_exsel_signal_t = signal<void()>;
  using keydown_exsel_slot_t = keydown_exsel_signal_t::slot_type;
  using keydown_kp_00_signal_t = signal<void()>;
  using keydown_kp_00_slot_t = keydown_kp_00_signal_t::slot_type;
  using keydown_kp_000_signal_t = signal<void()>;
  using keydown_kp_000_slot_t = keydown_kp_000_signal_t::slot_type;
  using keydown_thousandsseparator_signal_t = signal<void()>;
  using keydown_thousandsseparator_slot_t
    = keydown_thousandsseparator_signal_t::slot_type;
  using keydown_decimalseparator_signal_t = signal<void()>;
  using keydown_decimalseparator_slot_t
    = keydown_decimalseparator_signal_t::slot_type;
  using keydown_currencyunit_signal_t = signal<void()>;
  using keydown_currencyunit_slot_t = keydown_currencyunit_signal_t::slot_type;
  using keydown_currencysubunit_signal_t = signal<void()>;
  using keydown_currencysubunit_slot_t
    = keydown_currencysubunit_signal_t::slot_type;
  using keydown_kp_leftparen_signal_t = signal<void()>;
  using keydown_kp_leftparen_slot_t = keydown_kp_leftparen_signal_t::slot_type;
  using keydown_kp_rightparen_signal_t = signal<void()>;
  using keydown_kp_rightparen_slot_t
    = keydown_kp_rightparen_signal_t::slot_type;
  using keydown_kp_leftbrace_signal_t = signal<void()>;
  using keydown_kp_leftbrace_slot_t = keydown_kp_leftbrace_signal_t::slot_type;
  using keydown_kp_rightbrace_signal_t = signal<void()>;
  using keydown_kp_rightbrace_slot_t
    = keydown_kp_rightbrace_signal_t::slot_type;
  using keydown_kp_tab_signal_t = signal<void()>;
  using keydown_kp_tab_slot_t = keydown_kp_tab_signal_t::slot_type;
  using keydown_kp_backspace_signal_t = signal<void()>;
  using keydown_kp_backspace_slot_t = keydown_kp_backspace_signal_t::slot_type;
  using keydown_kp_a_signal_t = signal<void()>;
  using keydown_kp_a_slot_t = keydown_kp_a_signal_t::slot_type;
  using keydown_kp_b_signal_t = signal<void()>;
  using keydown_kp_b_slot_t = keydown_kp_b_signal_t::slot_type;
  using keydown_kp_c_signal_t = signal<void()>;
  using keydown_kp_c_slot_t = keydown_kp_c_signal_t::slot_type;
  using keydown_kp_d_signal_t = signal<void()>;
  using keydown_kp_d_slot_t = keydown_kp_d_signal_t::slot_type;
  using keydown_kp_e_signal_t = signal<void()>;
  using keydown_kp_e_slot_t = keydown_kp_e_signal_t::slot_type;
  using keydown_kp_f_signal_t = signal<void()>;
  using keydown_kp_f_slot_t = keydown_kp_f_signal_t::slot_type;
  using keydown_kp_xor_signal_t = signal<void()>;
  using keydown_kp_xor_slot_t = keydown_kp_xor_signal_t::slot_type;
  using keydown_kp_power_signal_t = signal<void()>;
  using keydown_kp_power_slot_t = keydown_kp_power_signal_t::slot_type;
  using keydown_kp_percent_signal_t = signal<void()>;
  using keydown_kp_percent_slot_t = keydown_kp_percent_signal_t::slot_type;
  using keydown_kp_less_signal_t = signal<void()>;
  using keydown_kp_less_slot_t = keydown_kp_less_signal_t::slot_type;
  using keydown_kp_greater_signal_t = signal<void()>;
  using keydown_kp_greater_slot_t = keydown_kp_greater_signal_t::slot_type;
  using keydown_kp_ampersand_signal_t = signal<void()>;
  using keydown_kp_ampersand_slot_t = keydown_kp_ampersand_signal_t::slot_type;
  using keydown_kp_dblampersand_signal_t = signal<void()>;
  using keydown_kp_dblampersand_slot_t
    = keydown_kp_dblampersand_signal_t::slot_type;
  using keydown_kp_verticalbar_signal_t = signal<void()>;
  using keydown_kp_verticalbar_slot_t
    = keydown_kp_verticalbar_signal_t::slot_type;
  using keydown_kp_dblverticalbar_signal_t = signal<void()>;
  using keydown_kp_dblverticalbar_slot_t
    = keydown_kp_dblverticalbar_signal_t::slot_type;
  using keydown_kp_colon_signal_t = signal<void()>;
  using keydown_kp_colon_slot_t = keydown_kp_colon_signal_t::slot_type;
  using keydown_kp_hash_signal_t = signal<void()>;
  using keydown_kp_hash_slot_t = keydown_kp_hash_signal_t::slot_type;
  using keydown_kp_space_signal_t = signal<void()>;
  using keydown_kp_space_slot_t = keydown_kp_space_signal_t::slot_type;
  using keydown_kp_at_signal_t = signal<void()>;
  using keydown_kp_at_slot_t = keydown_kp_at_signal_t::slot_type;
  using keydown_kp_exclam_signal_t = signal<void()>;
  using keydown_kp_exclam_slot_t = keydown_kp_exclam_signal_t::slot_type;
  using keydown_kp_memstore_signal_t = signal<void()>;
  using keydown_kp_memstore_slot_t = keydown_kp_memstore_signal_t::slot_type;
  using keydown_kp_memrecall_signal_t = signal<void()>;
  using keydown_kp_memrecall_slot_t = keydown_kp_memrecall_signal_t::slot_type;
  using keydown_kp_memclear_signal_t = signal<void()>;
  using keydown_kp_memclear_slot_t = keydown_kp_memclear_signal_t::slot_type;
  using keydown_kp_memadd_signal_t = signal<void()>;
  using keydown_kp_memadd_slot_t = keydown_kp_memadd_signal_t::slot_type;
  using keydown_kp_memsubtract_signal_t = signal<void()>;
  using keydown_kp_memsubtract_slot_t
    = keydown_kp_memsubtract_signal_t::slot_type;
  using keydown_kp_memmultiply_signal_t = signal<void()>;
  using keydown_kp_memmultiply_slot_t
    = keydown_kp_memmultiply_signal_t::slot_type;
  using keydown_kp_memdivide_signal_t = signal<void()>;
  using keydown_kp_memdivide_slot_t = keydown_kp_memdivide_signal_t::slot_type;
  using keydown_kp_plusminus_signal_t = signal<void()>;
  using keydown_kp_plusminus_slot_t = keydown_kp_plusminus_signal_t::slot_type;
  using keydown_kp_clear_signal_t = signal<void()>;
  using keydown_kp_clear_slot_t = keydown_kp_clear_signal_t::slot_type;
  using keydown_kp_clearentry_signal_t = signal<void()>;
  using keydown_kp_clearentry_slot_t
    = keydown_kp_clearentry_signal_t::slot_type;
  using keydown_kp_binary_signal_t = signal<void()>;
  using keydown_kp_binary_slot_t = keydown_kp_binary_signal_t::slot_type;
  using keydown_kp_octal_signal_t = signal<void()>;
  using keydown_kp_octal_slot_t = keydown_kp_octal_signal_t::slot_type;
  using keydown_kp_decimal_signal_t = signal<void()>;
  using keydown_kp_decimal_slot_t = keydown_kp_decimal_signal_t::slot_type;
  using keydown_kp_hexadecimal_signal_t = signal<void()>;
  using keydown_kp_hexadecimal_slot_t
    = keydown_kp_hexadecimal_signal_t::slot_type;
  using keydown_lctrl_signal_t = signal<void()>;
  using keydown_lctrl_slot_t = keydown_lctrl_signal_t::slot_type;
  using keydown_lshift_signal_t = signal<void()>;
  using keydown_lshift_slot_t = keydown_lshift_signal_t::slot_type;
  using keydown_lalt_signal_t = signal<void()>;
  using keydown_lalt_slot_t = keydown_lalt_signal_t::slot_type;
  using keydown_lgui_signal_t = signal<void()>;
  using keydown_lgui_slot_t = keydown_lgui_signal_t::slot_type;
  using keydown_rctrl_signal_t = signal<void()>;
  using keydown_rctrl_slot_t = keydown_rctrl_signal_t::slot_type;
  using keydown_rshift_signal_t = signal<void()>;
  using keydown_rshift_slot_t = keydown_rshift_signal_t::slot_type;
  using keydown_ralt_signal_t = signal<void()>;
  using keydown_ralt_slot_t = keydown_ralt_signal_t::slot_type;
  using keydown_rgui_signal_t = signal<void()>;
  using keydown_rgui_slot_t = keydown_rgui_signal_t::slot_type;
  using keydown_mode_signal_t = signal<void()>;
  using keydown_mode_slot_t = keydown_mode_signal_t::slot_type;
  using keydown_audionext_signal_t = signal<void()>;
  using keydown_audionext_slot_t = keydown_audionext_signal_t::slot_type;
  using keydown_audioprev_signal_t = signal<void()>;
  using keydown_audioprev_slot_t = keydown_audioprev_signal_t::slot_type;
  using keydown_audiostop_signal_t = signal<void()>;
  using keydown_audiostop_slot_t = keydown_audiostop_signal_t::slot_type;
  using keydown_audioplay_signal_t = signal<void()>;
  using keydown_audioplay_slot_t = keydown_audioplay_signal_t::slot_type;
  using keydown_audiomute_signal_t = signal<void()>;
  using keydown_audiomute_slot_t = keydown_audiomute_signal_t::slot_type;
  using keydown_mediaselect_signal_t = signal<void()>;
  using keydown_mediaselect_slot_t = keydown_mediaselect_signal_t::slot_type;
  using keydown_www_signal_t = signal<void()>;
  using keydown_www_slot_t = keydown_www_signal_t::slot_type;
  using keydown_mail_signal_t = signal<void()>;
  using keydown_mail_slot_t = keydown_mail_signal_t::slot_type;
  using keydown_calculator_signal_t = signal<void()>;
  using keydown_calculator_slot_t = keydown_calculator_signal_t::slot_type;
  using keydown_computer_signal_t = signal<void()>;
  using keydown_computer_slot_t = keydown_computer_signal_t::slot_type;
  using keydown_ac_search_signal_t = signal<void()>;
  using keydown_ac_search_slot_t = keydown_ac_search_signal_t::slot_type;
  using keydown_ac_home_signal_t = signal<void()>;
  using keydown_ac_home_slot_t = keydown_ac_home_signal_t::slot_type;
  using keydown_ac_back_signal_t = signal<void()>;
  using keydown_ac_back_slot_t = keydown_ac_back_signal_t::slot_type;
  using keydown_ac_forward_signal_t = signal<void()>;
  using keydown_ac_forward_slot_t = keydown_ac_forward_signal_t::slot_type;
  using keydown_ac_stop_signal_t = signal<void()>;
  using keydown_ac_stop_slot_t = keydown_ac_stop_signal_t::slot_type;
  using keydown_ac_refresh_signal_t = signal<void()>;
  using keydown_ac_refresh_slot_t = keydown_ac_refresh_signal_t::slot_type;
  using keydown_ac_bookmarks_signal_t = signal<void()>;
  using keydown_ac_bookmarks_slot_t = keydown_ac_bookmarks_signal_t::slot_type;
  using keydown_brightnessdown_signal_t = signal<void()>;
  using keydown_brightnessdown_slot_t
    = keydown_brightnessdown_signal_t::slot_type;
  using keydown_brightnessup_signal_t = signal<void()>;
  using keydown_brightnessup_slot_t = keydown_brightnessup_signal_t::slot_type;
  using keydown_displayswitch_signal_t = signal<void()>;
  using keydown_displayswitch_slot_t
    = keydown_displayswitch_signal_t::slot_type;
  using keydown_kbdillumtoggle_signal_t = signal<void()>;
  using keydown_kbdillumtoggle_slot_t
    = keydown_kbdillumtoggle_signal_t::slot_type;
  using keydown_kbdillumdown_signal_t = signal<void()>;
  using keydown_kbdillumdown_slot_t = keydown_kbdillumdown_signal_t::slot_type;
  using keydown_kbdillumup_signal_t = signal<void()>;
  using keydown_kbdillumup_slot_t = keydown_kbdillumup_signal_t::slot_type;
  using keydown_eject_signal_t = signal<void()>;
  using keydown_eject_slot_t = keydown_eject_signal_t::slot_type;
  using keydown_sleep_signal_t = signal<void()>;
  using keydown_sleep_slot_t = keydown_sleep_signal_t::slot_type;

  event_dispatch();

  void quit() const;
  void keydown_unknown() const;
  void keydown_backspace() const;
  void keydown_tab() const;
  void keydown_return() const;
  void keydown_escape() const;
  void keydown_space() const;
  void keydown_exclaim() const;
  void keydown_quotedbl() const;
  void keydown_hash() const;
  void keydown_dollar() const;
  void keydown_percent() const;
  void keydown_ampersand() const;
  void keydown_quote() const;
  void keydown_leftparen() const;
  void keydown_rightparen() const;
  void keydown_asterisk() const;
  void keydown_plus() const;
  void keydown_comma() const;
  void keydown_minus() const;
  void keydown_period() const;
  void keydown_slash() const;
  void keydown_0() const;
  void keydown_1() const;
  void keydown_2() const;
  void keydown_3() const;
  void keydown_4() const;
  void keydown_5() const;
  void keydown_6() const;
  void keydown_7() const;
  void keydown_8() const;
  void keydown_9() const;
  void keydown_colon() const;
  void keydown_semicolon() const;
  void keydown_less() const;
  void keydown_equals() const;
  void keydown_greater() const;
  void keydown_question() const;
  void keydown_at() const;
  void keydown_leftbracket() const;
  void keydown_backslash() const;
  void keydown_rightbracket() const;
  void keydown_caret() const;
  void keydown_underscore() const;
  void keydown_backquote() const;
  void keydown_a() const;
  void keydown_b() const;
  void keydown_c() const;
  void keydown_d() const;
  void keydown_e() const;
  void keydown_f() const;
  void keydown_g() const;
  void keydown_h() const;
  void keydown_i() const;
  void keydown_j() const;
  void keydown_k() const;
  void keydown_l() const;
  void keydown_m() const;
  void keydown_n() const;
  void keydown_o() const;
  void keydown_p() const;
  void keydown_q() const;
  void keydown_r() const;
  void keydown_s() const;
  void keydown_t() const;
  void keydown_u() const;
  void keydown_v() const;
  void keydown_w() const;
  void keydown_x() const;
  void keydown_y() const;
  void keydown_z() const;
  void keydown_delete() const;
  void keydown_capslock() const;
  void keydown_f1() const;
  void keydown_f2() const;
  void keydown_f3() const;
  void keydown_f4() const;
  void keydown_f5() const;
  void keydown_f6() const;
  void keydown_f7() const;
  void keydown_f8() const;
  void keydown_f9() const;
  void keydown_f10() const;
  void keydown_f11() const;
  void keydown_f12() const;
  void keydown_printscreen() const;
  void keydown_scrolllock() const;
  void keydown_pause() const;
  void keydown_insert() const;
  void keydown_home() const;
  void keydown_pageup() const;
  void keydown_end() const;
  void keydown_pagedown() const;
  void keydown_right() const;
  void keydown_left() const;
  void keydown_down() const;
  void keydown_up() const;
  void keydown_numlockclear() const;
  void keydown_kp_divide() const;
  void keydown_kp_multiply() const;
  void keydown_kp_minus() const;
  void keydown_kp_plus() const;
  void keydown_kp_enter() const;
  void keydown_kp_1() const;
  void keydown_kp_2() const;
  void keydown_kp_3() const;
  void keydown_kp_4() const;
  void keydown_kp_5() const;
  void keydown_kp_6() const;
  void keydown_kp_7() const;
  void keydown_kp_8() const;
  void keydown_kp_9() const;
  void keydown_kp_0() const;
  void keydown_kp_period() const;
  void keydown_application() const;
  void keydown_power() const;
  void keydown_kp_equals() const;
  void keydown_f13() const;
  void keydown_f14() const;
  void keydown_f15() const;
  void keydown_f16() const;
  void keydown_f17() const;
  void keydown_f18() const;
  void keydown_f19() const;
  void keydown_f20() const;
  void keydown_f21() const;
  void keydown_f22() const;
  void keydown_f23() const;
  void keydown_f24() const;
  void keydown_execute() const;
  void keydown_help() const;
  void keydown_menu() const;
  void keydown_select() const;
  void keydown_stop() const;
  void keydown_again() const;
  void keydown_undo() const;
  void keydown_cut() const;
  void keydown_copy() const;
  void keydown_paste() const;
  void keydown_find() const;
  void keydown_mute() const;
  void keydown_volumeup() const;
  void keydown_volumedown() const;
  void keydown_kp_comma() const;
  void keydown_kp_equalsas400() const;
  void keydown_alterase() const;
  void keydown_sysreq() const;
  void keydown_cancel() const;
  void keydown_clear() const;
  void keydown_prior() const;
  void keydown_return2() const;
  void keydown_separator() const;
  void keydown_out() const;
  void keydown_oper() const;
  void keydown_clearagain() const;
  void keydown_crsel() const;
  void keydown_exsel() const;
  void keydown_kp_00() const;
  void keydown_kp_000() const;
  void keydown_thousandsseparator() const;
  void keydown_decimalseparator() const;
  void keydown_currencyunit() const;
  void keydown_currencysubunit() const;
  void keydown_kp_leftparen() const;
  void keydown_kp_rightparen() const;
  void keydown_kp_leftbrace() const;
  void keydown_kp_rightbrace() const;
  void keydown_kp_tab() const;
  void keydown_kp_backspace() const;
  void keydown_kp_a() const;
  void keydown_kp_b() const;
  void keydown_kp_c() const;
  void keydown_kp_d() const;
  void keydown_kp_e() const;
  void keydown_kp_f() const;
  void keydown_kp_xor() const;
  void keydown_kp_power() const;
  void keydown_kp_percent() const;
  void keydown_kp_less() const;
  void keydown_kp_greater() const;
  void keydown_kp_ampersand() const;
  void keydown_kp_dblampersand() const;
  void keydown_kp_verticalbar() const;
  void keydown_kp_dblverticalbar() const;
  void keydown_kp_colon() const;
  void keydown_kp_hash() const;
  void keydown_kp_space() const;
  void keydown_kp_at() const;
  void keydown_kp_exclam() const;
  void keydown_kp_memstore() const;
  void keydown_kp_memrecall() const;
  void keydown_kp_memclear() const;
  void keydown_kp_memadd() const;
  void keydown_kp_memsubtract() const;
  void keydown_kp_memmultiply() const;
  void keydown_kp_memdivide() const;
  void keydown_kp_plusminus() const;
  void keydown_kp_clear() const;
  void keydown_kp_clearentry() const;
  void keydown_kp_binary() const;
  void keydown_kp_octal() const;
  void keydown_kp_decimal() const;
  void keydown_kp_hexadecimal() const;
  void keydown_lctrl() const;
  void keydown_lshift() const;
  void keydown_lalt() const;
  void keydown_lgui() const;
  void keydown_rctrl() const;
  void keydown_rshift() const;
  void keydown_ralt() const;
  void keydown_rgui() const;
  void keydown_mode() const;
  void keydown_audionext() const;
  void keydown_audioprev() const;
  void keydown_audiostop() const;
  void keydown_audioplay() const;
  void keydown_audiomute() const;
  void keydown_mediaselect() const;
  void keydown_www() const;
  void keydown_mail() const;
  void keydown_calculator() const;
  void keydown_computer() const;
  void keydown_ac_search() const;
  void keydown_ac_home() const;
  void keydown_ac_back() const;
  void keydown_ac_forward() const;
  void keydown_ac_stop() const;
  void keydown_ac_refresh() const;
  void keydown_ac_bookmarks() const;
  void keydown_brightnessdown() const;
  void keydown_brightnessup() const;
  void keydown_displayswitch() const;
  void keydown_kbdillumtoggle() const;
  void keydown_kbdillumdown() const;
  void keydown_kbdillumup() const;
  void keydown_eject() const;
  void keydown_sleep() const;

  connection on_quit(quit_slot_t const& op);
  connection on_keydown_unknown(keydown_unknown_slot_t const& op);
  connection on_keydown_backspace(keydown_backspace_slot_t const& op);
  connection on_keydown_tab(keydown_tab_slot_t const& op);
  connection on_keydown_return(keydown_return_slot_t const& op);
  connection on_keydown_escape(keydown_escape_slot_t const& op);
  connection on_keydown_space(keydown_space_slot_t const& op);
  connection on_keydown_exclaim(keydown_exclaim_slot_t const& op);
  connection on_keydown_quotedbl(keydown_quotedbl_slot_t const& op);
  connection on_keydown_hash(keydown_hash_slot_t const& op);
  connection on_keydown_dollar(keydown_dollar_slot_t const& op);
  connection on_keydown_percent(keydown_percent_slot_t const& op);
  connection on_keydown_ampersand(keydown_ampersand_slot_t const& op);
  connection on_keydown_quote(keydown_quote_slot_t const& op);
  connection on_keydown_leftparen(keydown_leftparen_slot_t const& op);
  connection on_keydown_rightparen(keydown_rightparen_slot_t const& op);
  connection on_keydown_asterisk(keydown_asterisk_slot_t const& op);
  connection on_keydown_plus(keydown_plus_slot_t const& op);
  connection on_keydown_comma(keydown_comma_slot_t const& op);
  connection on_keydown_minus(keydown_minus_slot_t const& op);
  connection on_keydown_period(keydown_period_slot_t const& op);
  connection on_keydown_slash(keydown_slash_slot_t const& op);
  connection on_keydown_0(keydown_0_slot_t const& op);
  connection on_keydown_1(keydown_1_slot_t const& op);
  connection on_keydown_2(keydown_2_slot_t const& op);
  connection on_keydown_3(keydown_3_slot_t const& op);
  connection on_keydown_4(keydown_4_slot_t const& op);
  connection on_keydown_5(keydown_5_slot_t const& op);
  connection on_keydown_6(keydown_6_slot_t const& op);
  connection on_keydown_7(keydown_7_slot_t const& op);
  connection on_keydown_8(keydown_8_slot_t const& op);
  connection on_keydown_9(keydown_9_slot_t const& op);
  connection on_keydown_colon(keydown_colon_slot_t const& op);
  connection on_keydown_semicolon(keydown_semicolon_slot_t const& op);
  connection on_keydown_less(keydown_less_slot_t const& op);
  connection on_keydown_equals(keydown_equals_slot_t const& op);
  connection on_keydown_greater(keydown_greater_slot_t const& op);
  connection on_keydown_question(keydown_question_slot_t const& op);
  connection on_keydown_at(keydown_at_slot_t const& op);
  connection on_keydown_leftbracket(keydown_leftbracket_slot_t const& op);
  connection on_keydown_backslash(keydown_backslash_slot_t const& op);
  connection on_keydown_rightbracket(keydown_rightbracket_slot_t const& op);
  connection on_keydown_caret(keydown_caret_slot_t const& op);
  connection on_keydown_underscore(keydown_underscore_slot_t const& op);
  connection on_keydown_backquote(keydown_backquote_slot_t const& op);
  connection on_keydown_a(keydown_a_slot_t const& op);
  connection on_keydown_b(keydown_b_slot_t const& op);
  connection on_keydown_c(keydown_c_slot_t const& op);
  connection on_keydown_d(keydown_d_slot_t const& op);
  connection on_keydown_e(keydown_e_slot_t const& op);
  connection on_keydown_f(keydown_f_slot_t const& op);
  connection on_keydown_g(keydown_g_slot_t const& op);
  connection on_keydown_h(keydown_h_slot_t const& op);
  connection on_keydown_i(keydown_i_slot_t const& op);
  connection on_keydown_j(keydown_j_slot_t const& op);
  connection on_keydown_k(keydown_k_slot_t const& op);
  connection on_keydown_l(keydown_l_slot_t const& op);
  connection on_keydown_m(keydown_m_slot_t const& op);
  connection on_keydown_n(keydown_n_slot_t const& op);
  connection on_keydown_o(keydown_o_slot_t const& op);
  connection on_keydown_p(keydown_p_slot_t const& op);
  connection on_keydown_q(keydown_q_slot_t const& op);
  connection on_keydown_r(keydown_r_slot_t const& op);
  connection on_keydown_s(keydown_s_slot_t const& op);
  connection on_keydown_t(keydown_t_slot_t const& op);
  connection on_keydown_u(keydown_u_slot_t const& op);
  connection on_keydown_v(keydown_v_slot_t const& op);
  connection on_keydown_w(keydown_w_slot_t const& op);
  connection on_keydown_x(keydown_x_slot_t const& op);
  connection on_keydown_y(keydown_y_slot_t const& op);
  connection on_keydown_z(keydown_z_slot_t const& op);
  connection on_keydown_delete(keydown_delete_slot_t const& op);
  connection on_keydown_capslock(keydown_capslock_slot_t const& op);
  connection on_keydown_f1(keydown_f1_slot_t const& op);
  connection on_keydown_f2(keydown_f2_slot_t const& op);
  connection on_keydown_f3(keydown_f3_slot_t const& op);
  connection on_keydown_f4(keydown_f4_slot_t const& op);
  connection on_keydown_f5(keydown_f5_slot_t const& op);
  connection on_keydown_f6(keydown_f6_slot_t const& op);
  connection on_keydown_f7(keydown_f7_slot_t const& op);
  connection on_keydown_f8(keydown_f8_slot_t const& op);
  connection on_keydown_f9(keydown_f9_slot_t const& op);
  connection on_keydown_f10(keydown_f10_slot_t const& op);
  connection on_keydown_f11(keydown_f11_slot_t const& op);
  connection on_keydown_f12(keydown_f12_slot_t const& op);
  connection on_keydown_printscreen(keydown_printscreen_slot_t const& op);
  connection on_keydown_scrolllock(keydown_scrolllock_slot_t const& op);
  connection on_keydown_pause(keydown_pause_slot_t const& op);
  connection on_keydown_insert(keydown_insert_slot_t const& op);
  connection on_keydown_home(keydown_home_slot_t const& op);
  connection on_keydown_pageup(keydown_pageup_slot_t const& op);
  connection on_keydown_end(keydown_end_slot_t const& op);
  connection on_keydown_pagedown(keydown_pagedown_slot_t const& op);
  connection on_keydown_right(keydown_right_slot_t const& op);
  connection on_keydown_left(keydown_left_slot_t const& op);
  connection on_keydown_down(keydown_down_slot_t const& op);
  connection on_keydown_up(keydown_up_slot_t const& op);
  connection on_keydown_numlockclear(keydown_numlockclear_slot_t const& op);
  connection on_keydown_kp_divide(keydown_kp_divide_slot_t const& op);
  connection on_keydown_kp_multiply(keydown_kp_multiply_slot_t const& op);
  connection on_keydown_kp_minus(keydown_kp_minus_slot_t const& op);
  connection on_keydown_kp_plus(keydown_kp_plus_slot_t const& op);
  connection on_keydown_kp_enter(keydown_kp_enter_slot_t const& op);
  connection on_keydown_kp_1(keydown_kp_1_slot_t const& op);
  connection on_keydown_kp_2(keydown_kp_2_slot_t const& op);
  connection on_keydown_kp_3(keydown_kp_3_slot_t const& op);
  connection on_keydown_kp_4(keydown_kp_4_slot_t const& op);
  connection on_keydown_kp_5(keydown_kp_5_slot_t const& op);
  connection on_keydown_kp_6(keydown_kp_6_slot_t const& op);
  connection on_keydown_kp_7(keydown_kp_7_slot_t const& op);
  connection on_keydown_kp_8(keydown_kp_8_slot_t const& op);
  connection on_keydown_kp_9(keydown_kp_9_slot_t const& op);
  connection on_keydown_kp_0(keydown_kp_0_slot_t const& op);
  connection on_keydown_kp_period(keydown_kp_period_slot_t const& op);
  connection on_keydown_application(keydown_application_slot_t const& op);
  connection on_keydown_power(keydown_power_slot_t const& op);
  connection on_keydown_kp_equals(keydown_kp_equals_slot_t const& op);
  connection on_keydown_f13(keydown_f13_slot_t const& op);
  connection on_keydown_f14(keydown_f14_slot_t const& op);
  connection on_keydown_f15(keydown_f15_slot_t const& op);
  connection on_keydown_f16(keydown_f16_slot_t const& op);
  connection on_keydown_f17(keydown_f17_slot_t const& op);
  connection on_keydown_f18(keydown_f18_slot_t const& op);
  connection on_keydown_f19(keydown_f19_slot_t const& op);
  connection on_keydown_f20(keydown_f20_slot_t const& op);
  connection on_keydown_f21(keydown_f21_slot_t const& op);
  connection on_keydown_f22(keydown_f22_slot_t const& op);
  connection on_keydown_f23(keydown_f23_slot_t const& op);
  connection on_keydown_f24(keydown_f24_slot_t const& op);
  connection on_keydown_execute(keydown_execute_slot_t const& op);
  connection on_keydown_help(keydown_help_slot_t const& op);
  connection on_keydown_menu(keydown_menu_slot_t const& op);
  connection on_keydown_select(keydown_select_slot_t const& op);
  connection on_keydown_stop(keydown_stop_slot_t const& op);
  connection on_keydown_again(keydown_again_slot_t const& op);
  connection on_keydown_undo(keydown_undo_slot_t const& op);
  connection on_keydown_cut(keydown_cut_slot_t const& op);
  connection on_keydown_copy(keydown_copy_slot_t const& op);
  connection on_keydown_paste(keydown_paste_slot_t const& op);
  connection on_keydown_find(keydown_find_slot_t const& op);
  connection on_keydown_mute(keydown_mute_slot_t const& op);
  connection on_keydown_volumeup(keydown_volumeup_slot_t const& op);
  connection on_keydown_volumedown(keydown_volumedown_slot_t const& op);
  connection on_keydown_kp_comma(keydown_kp_comma_slot_t const& op);
  connection on_keydown_kp_equalsas400(
    keydown_kp_equalsas400_slot_t const& op);
  connection on_keydown_alterase(keydown_alterase_slot_t const& op);
  connection on_keydown_sysreq(keydown_sysreq_slot_t const& op);
  connection on_keydown_cancel(keydown_cancel_slot_t const& op);
  connection on_keydown_clear(keydown_clear_slot_t const& op);
  connection on_keydown_prior(keydown_prior_slot_t const& op);
  connection on_keydown_return2(keydown_return2_slot_t const& op);
  connection on_keydown_separator(keydown_separator_slot_t const& op);
  connection on_keydown_out(keydown_out_slot_t const& op);
  connection on_keydown_oper(keydown_oper_slot_t const& op);
  connection on_keydown_clearagain(keydown_clearagain_slot_t const& op);
  connection on_keydown_crsel(keydown_crsel_slot_t const& op);
  connection on_keydown_exsel(keydown_exsel_slot_t const& op);
  connection on_keydown_kp_00(keydown_kp_00_slot_t const& op);
  connection on_keydown_kp_000(keydown_kp_000_slot_t const& op);
  connection on_keydown_thousandsseparator(
    keydown_thousandsseparator_slot_t const& op);
  connection on_keydown_decimalseparator(
    keydown_decimalseparator_slot_t const& op);
  connection on_keydown_currencyunit(keydown_currencyunit_slot_t const& op);
  connection on_keydown_currencysubunit(
    keydown_currencysubunit_slot_t const& op);
  connection on_keydown_kp_leftparen(keydown_kp_leftparen_slot_t const& op);
  connection on_keydown_kp_rightparen(keydown_kp_rightparen_slot_t const& op);
  connection on_keydown_kp_leftbrace(keydown_kp_leftbrace_slot_t const& op);
  connection on_keydown_kp_rightbrace(keydown_kp_rightbrace_slot_t const& op);
  connection on_keydown_kp_tab(keydown_kp_tab_slot_t const& op);
  connection on_keydown_kp_backspace(keydown_kp_backspace_slot_t const& op);
  connection on_keydown_kp_a(keydown_kp_a_slot_t const& op);
  connection on_keydown_kp_b(keydown_kp_b_slot_t const& op);
  connection on_keydown_kp_c(keydown_kp_c_slot_t const& op);
  connection on_keydown_kp_d(keydown_kp_d_slot_t const& op);
  connection on_keydown_kp_e(keydown_kp_e_slot_t const& op);
  connection on_keydown_kp_f(keydown_kp_f_slot_t const& op);
  connection on_keydown_kp_xor(keydown_kp_xor_slot_t const& op);
  connection on_keydown_kp_power(keydown_kp_power_slot_t const& op);
  connection on_keydown_kp_percent(keydown_kp_percent_slot_t const& op);
  connection on_keydown_kp_less(keydown_kp_less_slot_t const& op);
  connection on_keydown_kp_greater(keydown_kp_greater_slot_t const& op);
  connection on_keydown_kp_ampersand(keydown_kp_ampersand_slot_t const& op);
  connection on_keydown_kp_dblampersand(
    keydown_kp_dblampersand_slot_t const& op);
  connection on_keydown_kp_verticalbar(
    keydown_kp_verticalbar_slot_t const& op);
  connection on_keydown_kp_dblverticalbar(
    keydown_kp_dblverticalbar_slot_t const& op);
  connection on_keydown_kp_colon(keydown_kp_colon_slot_t const& op);
  connection on_keydown_kp_hash(keydown_kp_hash_slot_t const& op);
  connection on_keydown_kp_space(keydown_kp_space_slot_t const& op);
  connection on_keydown_kp_at(keydown_kp_at_slot_t const& op);
  connection on_keydown_kp_exclam(keydown_kp_exclam_slot_t const& op);
  connection on_keydown_kp_memstore(keydown_kp_memstore_slot_t const& op);
  connection on_keydown_kp_memrecall(keydown_kp_memrecall_slot_t const& op);
  connection on_keydown_kp_memclear(keydown_kp_memclear_slot_t const& op);
  connection on_keydown_kp_memadd(keydown_kp_memadd_slot_t const& op);
  connection on_keydown_kp_memsubtract(
    keydown_kp_memsubtract_slot_t const& op);
  connection on_keydown_kp_memmultiply(
    keydown_kp_memmultiply_slot_t const& op);
  connection on_keydown_kp_memdivide(keydown_kp_memdivide_slot_t const& op);
  connection on_keydown_kp_plusminus(keydown_kp_plusminus_slot_t const& op);
  connection on_keydown_kp_clear(keydown_kp_clear_slot_t const& op);
  connection on_keydown_kp_clearentry(keydown_kp_clearentry_slot_t const& op);
  connection on_keydown_kp_binary(keydown_kp_binary_slot_t const& op);
  connection on_keydown_kp_octal(keydown_kp_octal_slot_t const& op);
  connection on_keydown_kp_decimal(keydown_kp_decimal_slot_t const& op);
  connection on_keydown_kp_hexadecimal(
    keydown_kp_hexadecimal_slot_t const& op);
  connection on_keydown_lctrl(keydown_lctrl_slot_t const& op);
  connection on_keydown_lshift(keydown_lshift_slot_t const& op);
  connection on_keydown_lalt(keydown_lalt_slot_t const& op);
  connection on_keydown_lgui(keydown_lgui_slot_t const& op);
  connection on_keydown_rctrl(keydown_rctrl_slot_t const& op);
  connection on_keydown_rshift(keydown_rshift_slot_t const& op);
  connection on_keydown_ralt(keydown_ralt_slot_t const& op);
  connection on_keydown_rgui(keydown_rgui_slot_t const& op);
  connection on_keydown_mode(keydown_mode_slot_t const& op);
  connection on_keydown_audionext(keydown_audionext_slot_t const& op);
  connection on_keydown_audioprev(keydown_audioprev_slot_t const& op);
  connection on_keydown_audiostop(keydown_audiostop_slot_t const& op);
  connection on_keydown_audioplay(keydown_audioplay_slot_t const& op);
  connection on_keydown_audiomute(keydown_audiomute_slot_t const& op);
  connection on_keydown_mediaselect(keydown_mediaselect_slot_t const& op);
  connection on_keydown_www(keydown_www_slot_t const& op);
  connection on_keydown_mail(keydown_mail_slot_t const& op);
  connection on_keydown_calculator(keydown_calculator_slot_t const& op);
  connection on_keydown_computer(keydown_computer_slot_t const& op);
  connection on_keydown_ac_search(keydown_ac_search_slot_t const& op);
  connection on_keydown_ac_home(keydown_ac_home_slot_t const& op);
  connection on_keydown_ac_back(keydown_ac_back_slot_t const& op);
  connection on_keydown_ac_forward(keydown_ac_forward_slot_t const& op);
  connection on_keydown_ac_stop(keydown_ac_stop_slot_t const& op);
  connection on_keydown_ac_refresh(keydown_ac_refresh_slot_t const& op);
  connection on_keydown_ac_bookmarks(keydown_ac_bookmarks_slot_t const& op);
  connection on_keydown_brightnessdown(
    keydown_brightnessdown_slot_t const& op);
  connection on_keydown_brightnessup(keydown_brightnessup_slot_t const& op);
  connection on_keydown_displayswitch(keydown_displayswitch_slot_t const& op);
  connection on_keydown_kbdillumtoggle(
    keydown_kbdillumtoggle_slot_t const& op);
  connection on_keydown_kbdillumdown(keydown_kbdillumdown_slot_t const& op);
  connection on_keydown_kbdillumup(keydown_kbdillumup_slot_t const& op);
  connection on_keydown_eject(keydown_eject_slot_t const& op);
  connection on_keydown_sleep(keydown_sleep_slot_t const& op);

private:
  quit_signal_t quit_signal;
  keydown_unknown_signal_t keydown_unknown_signal;
  keydown_backspace_signal_t keydown_backspace_signal;
  keydown_tab_signal_t keydown_tab_signal;
  keydown_return_signal_t keydown_return_signal;
  keydown_escape_signal_t keydown_escape_signal;
  keydown_space_signal_t keydown_space_signal;
  keydown_exclaim_signal_t keydown_exclaim_signal;
  keydown_quotedbl_signal_t keydown_quotedbl_signal;
  keydown_hash_signal_t keydown_hash_signal;
  keydown_dollar_signal_t keydown_dollar_signal;
  keydown_percent_signal_t keydown_percent_signal;
  keydown_ampersand_signal_t keydown_ampersand_signal;
  keydown_quote_signal_t keydown_quote_signal;
  keydown_leftparen_signal_t keydown_leftparen_signal;
  keydown_rightparen_signal_t keydown_rightparen_signal;
  keydown_asterisk_signal_t keydown_asterisk_signal;
  keydown_plus_signal_t keydown_plus_signal;
  keydown_comma_signal_t keydown_comma_signal;
  keydown_minus_signal_t keydown_minus_signal;
  keydown_period_signal_t keydown_period_signal;
  keydown_slash_signal_t keydown_slash_signal;
  keydown_0_signal_t keydown_0_signal;
  keydown_1_signal_t keydown_1_signal;
  keydown_2_signal_t keydown_2_signal;
  keydown_3_signal_t keydown_3_signal;
  keydown_4_signal_t keydown_4_signal;
  keydown_5_signal_t keydown_5_signal;
  keydown_6_signal_t keydown_6_signal;
  keydown_7_signal_t keydown_7_signal;
  keydown_8_signal_t keydown_8_signal;
  keydown_9_signal_t keydown_9_signal;
  keydown_colon_signal_t keydown_colon_signal;
  keydown_semicolon_signal_t keydown_semicolon_signal;
  keydown_less_signal_t keydown_less_signal;
  keydown_equals_signal_t keydown_equals_signal;
  keydown_greater_signal_t keydown_greater_signal;
  keydown_question_signal_t keydown_question_signal;
  keydown_at_signal_t keydown_at_signal;
  keydown_leftbracket_signal_t keydown_leftbracket_signal;
  keydown_backslash_signal_t keydown_backslash_signal;
  keydown_rightbracket_signal_t keydown_rightbracket_signal;
  keydown_caret_signal_t keydown_caret_signal;
  keydown_underscore_signal_t keydown_underscore_signal;
  keydown_backquote_signal_t keydown_backquote_signal;
  keydown_a_signal_t keydown_a_signal;
  keydown_b_signal_t keydown_b_signal;
  keydown_c_signal_t keydown_c_signal;
  keydown_d_signal_t keydown_d_signal;
  keydown_e_signal_t keydown_e_signal;
  keydown_f_signal_t keydown_f_signal;
  keydown_g_signal_t keydown_g_signal;
  keydown_h_signal_t keydown_h_signal;
  keydown_i_signal_t keydown_i_signal;
  keydown_j_signal_t keydown_j_signal;
  keydown_k_signal_t keydown_k_signal;
  keydown_l_signal_t keydown_l_signal;
  keydown_m_signal_t keydown_m_signal;
  keydown_n_signal_t keydown_n_signal;
  keydown_o_signal_t keydown_o_signal;
  keydown_p_signal_t keydown_p_signal;
  keydown_q_signal_t keydown_q_signal;
  keydown_r_signal_t keydown_r_signal;
  keydown_s_signal_t keydown_s_signal;
  keydown_t_signal_t keydown_t_signal;
  keydown_u_signal_t keydown_u_signal;
  keydown_v_signal_t keydown_v_signal;
  keydown_w_signal_t keydown_w_signal;
  keydown_x_signal_t keydown_x_signal;
  keydown_y_signal_t keydown_y_signal;
  keydown_z_signal_t keydown_z_signal;
  keydown_delete_signal_t keydown_delete_signal;
  keydown_capslock_signal_t keydown_capslock_signal;
  keydown_f1_signal_t keydown_f1_signal;
  keydown_f2_signal_t keydown_f2_signal;
  keydown_f3_signal_t keydown_f3_signal;
  keydown_f4_signal_t keydown_f4_signal;
  keydown_f5_signal_t keydown_f5_signal;
  keydown_f6_signal_t keydown_f6_signal;
  keydown_f7_signal_t keydown_f7_signal;
  keydown_f8_signal_t keydown_f8_signal;
  keydown_f9_signal_t keydown_f9_signal;
  keydown_f10_signal_t keydown_f10_signal;
  keydown_f11_signal_t keydown_f11_signal;
  keydown_f12_signal_t keydown_f12_signal;
  keydown_printscreen_signal_t keydown_printscreen_signal;
  keydown_scrolllock_signal_t keydown_scrolllock_signal;
  keydown_pause_signal_t keydown_pause_signal;
  keydown_insert_signal_t keydown_insert_signal;
  keydown_home_signal_t keydown_home_signal;
  keydown_pageup_signal_t keydown_pageup_signal;
  keydown_end_signal_t keydown_end_signal;
  keydown_pagedown_signal_t keydown_pagedown_signal;
  keydown_right_signal_t keydown_right_signal;
  keydown_left_signal_t keydown_left_signal;
  keydown_down_signal_t keydown_down_signal;
  keydown_up_signal_t keydown_up_signal;
  keydown_numlockclear_signal_t keydown_numlockclear_signal;
  keydown_kp_divide_signal_t keydown_kp_divide_signal;
  keydown_kp_multiply_signal_t keydown_kp_multiply_signal;
  keydown_kp_minus_signal_t keydown_kp_minus_signal;
  keydown_kp_plus_signal_t keydown_kp_plus_signal;
  keydown_kp_enter_signal_t keydown_kp_enter_signal;
  keydown_kp_1_signal_t keydown_kp_1_signal;
  keydown_kp_2_signal_t keydown_kp_2_signal;
  keydown_kp_3_signal_t keydown_kp_3_signal;
  keydown_kp_4_signal_t keydown_kp_4_signal;
  keydown_kp_5_signal_t keydown_kp_5_signal;
  keydown_kp_6_signal_t keydown_kp_6_signal;
  keydown_kp_7_signal_t keydown_kp_7_signal;
  keydown_kp_8_signal_t keydown_kp_8_signal;
  keydown_kp_9_signal_t keydown_kp_9_signal;
  keydown_kp_0_signal_t keydown_kp_0_signal;
  keydown_kp_period_signal_t keydown_kp_period_signal;
  keydown_application_signal_t keydown_application_signal;
  keydown_power_signal_t keydown_power_signal;
  keydown_kp_equals_signal_t keydown_kp_equals_signal;
  keydown_f13_signal_t keydown_f13_signal;
  keydown_f14_signal_t keydown_f14_signal;
  keydown_f15_signal_t keydown_f15_signal;
  keydown_f16_signal_t keydown_f16_signal;
  keydown_f17_signal_t keydown_f17_signal;
  keydown_f18_signal_t keydown_f18_signal;
  keydown_f19_signal_t keydown_f19_signal;
  keydown_f20_signal_t keydown_f20_signal;
  keydown_f21_signal_t keydown_f21_signal;
  keydown_f22_signal_t keydown_f22_signal;
  keydown_f23_signal_t keydown_f23_signal;
  keydown_f24_signal_t keydown_f24_signal;
  keydown_execute_signal_t keydown_execute_signal;
  keydown_help_signal_t keydown_help_signal;
  keydown_menu_signal_t keydown_menu_signal;
  keydown_select_signal_t keydown_select_signal;
  keydown_stop_signal_t keydown_stop_signal;
  keydown_again_signal_t keydown_again_signal;
  keydown_undo_signal_t keydown_undo_signal;
  keydown_cut_signal_t keydown_cut_signal;
  keydown_copy_signal_t keydown_copy_signal;
  keydown_paste_signal_t keydown_paste_signal;
  keydown_find_signal_t keydown_find_signal;
  keydown_mute_signal_t keydown_mute_signal;
  keydown_volumeup_signal_t keydown_volumeup_signal;
  keydown_volumedown_signal_t keydown_volumedown_signal;
  keydown_kp_comma_signal_t keydown_kp_comma_signal;
  keydown_kp_equalsas400_signal_t keydown_kp_equalsas400_signal;
  keydown_alterase_signal_t keydown_alterase_signal;
  keydown_sysreq_signal_t keydown_sysreq_signal;
  keydown_cancel_signal_t keydown_cancel_signal;
  keydown_clear_signal_t keydown_clear_signal;
  keydown_prior_signal_t keydown_prior_signal;
  keydown_return2_signal_t keydown_return2_signal;
  keydown_separator_signal_t keydown_separator_signal;
  keydown_out_signal_t keydown_out_signal;
  keydown_oper_signal_t keydown_oper_signal;
  keydown_clearagain_signal_t keydown_clearagain_signal;
  keydown_crsel_signal_t keydown_crsel_signal;
  keydown_exsel_signal_t keydown_exsel_signal;
  keydown_kp_00_signal_t keydown_kp_00_signal;
  keydown_kp_000_signal_t keydown_kp_000_signal;
  keydown_thousandsseparator_signal_t keydown_thousandsseparator_signal;
  keydown_decimalseparator_signal_t keydown_decimalseparator_signal;
  keydown_currencyunit_signal_t keydown_currencyunit_signal;
  keydown_currencysubunit_signal_t keydown_currencysubunit_signal;
  keydown_kp_leftparen_signal_t keydown_kp_leftparen_signal;
  keydown_kp_rightparen_signal_t keydown_kp_rightparen_signal;
  keydown_kp_leftbrace_signal_t keydown_kp_leftbrace_signal;
  keydown_kp_rightbrace_signal_t keydown_kp_rightbrace_signal;
  keydown_kp_tab_signal_t keydown_kp_tab_signal;
  keydown_kp_backspace_signal_t keydown_kp_backspace_signal;
  keydown_kp_a_signal_t keydown_kp_a_signal;
  keydown_kp_b_signal_t keydown_kp_b_signal;
  keydown_kp_c_signal_t keydown_kp_c_signal;
  keydown_kp_d_signal_t keydown_kp_d_signal;
  keydown_kp_e_signal_t keydown_kp_e_signal;
  keydown_kp_f_signal_t keydown_kp_f_signal;
  keydown_kp_xor_signal_t keydown_kp_xor_signal;
  keydown_kp_power_signal_t keydown_kp_power_signal;
  keydown_kp_percent_signal_t keydown_kp_percent_signal;
  keydown_kp_less_signal_t keydown_kp_less_signal;
  keydown_kp_greater_signal_t keydown_kp_greater_signal;
  keydown_kp_ampersand_signal_t keydown_kp_ampersand_signal;
  keydown_kp_dblampersand_signal_t keydown_kp_dblampersand_signal;
  keydown_kp_verticalbar_signal_t keydown_kp_verticalbar_signal;
  keydown_kp_dblverticalbar_signal_t keydown_kp_dblverticalbar_signal;
  keydown_kp_colon_signal_t keydown_kp_colon_signal;
  keydown_kp_hash_signal_t keydown_kp_hash_signal;
  keydown_kp_space_signal_t keydown_kp_space_signal;
  keydown_kp_at_signal_t keydown_kp_at_signal;
  keydown_kp_exclam_signal_t keydown_kp_exclam_signal;
  keydown_kp_memstore_signal_t keydown_kp_memstore_signal;
  keydown_kp_memrecall_signal_t keydown_kp_memrecall_signal;
  keydown_kp_memclear_signal_t keydown_kp_memclear_signal;
  keydown_kp_memadd_signal_t keydown_kp_memadd_signal;
  keydown_kp_memsubtract_signal_t keydown_kp_memsubtract_signal;
  keydown_kp_memmultiply_signal_t keydown_kp_memmultiply_signal;
  keydown_kp_memdivide_signal_t keydown_kp_memdivide_signal;
  keydown_kp_plusminus_signal_t keydown_kp_plusminus_signal;
  keydown_kp_clear_signal_t keydown_kp_clear_signal;
  keydown_kp_clearentry_signal_t keydown_kp_clearentry_signal;
  keydown_kp_binary_signal_t keydown_kp_binary_signal;
  keydown_kp_octal_signal_t keydown_kp_octal_signal;
  keydown_kp_decimal_signal_t keydown_kp_decimal_signal;
  keydown_kp_hexadecimal_signal_t keydown_kp_hexadecimal_signal;
  keydown_lctrl_signal_t keydown_lctrl_signal;
  keydown_lshift_signal_t keydown_lshift_signal;
  keydown_lalt_signal_t keydown_lalt_signal;
  keydown_lgui_signal_t keydown_lgui_signal;
  keydown_rctrl_signal_t keydown_rctrl_signal;
  keydown_rshift_signal_t keydown_rshift_signal;
  keydown_ralt_signal_t keydown_ralt_signal;
  keydown_rgui_signal_t keydown_rgui_signal;
  keydown_mode_signal_t keydown_mode_signal;
  keydown_audionext_signal_t keydown_audionext_signal;
  keydown_audioprev_signal_t keydown_audioprev_signal;
  keydown_audiostop_signal_t keydown_audiostop_signal;
  keydown_audioplay_signal_t keydown_audioplay_signal;
  keydown_audiomute_signal_t keydown_audiomute_signal;
  keydown_mediaselect_signal_t keydown_mediaselect_signal;
  keydown_www_signal_t keydown_www_signal;
  keydown_mail_signal_t keydown_mail_signal;
  keydown_calculator_signal_t keydown_calculator_signal;
  keydown_computer_signal_t keydown_computer_signal;
  keydown_ac_search_signal_t keydown_ac_search_signal;
  keydown_ac_home_signal_t keydown_ac_home_signal;
  keydown_ac_back_signal_t keydown_ac_back_signal;
  keydown_ac_forward_signal_t keydown_ac_forward_signal;
  keydown_ac_stop_signal_t keydown_ac_stop_signal;
  keydown_ac_refresh_signal_t keydown_ac_refresh_signal;
  keydown_ac_bookmarks_signal_t keydown_ac_bookmarks_signal;
  keydown_brightnessdown_signal_t keydown_brightnessdown_signal;
  keydown_brightnessup_signal_t keydown_brightnessup_signal;
  keydown_displayswitch_signal_t keydown_displayswitch_signal;
  keydown_kbdillumtoggle_signal_t keydown_kbdillumtoggle_signal;
  keydown_kbdillumdown_signal_t keydown_kbdillumdown_signal;
  keydown_kbdillumup_signal_t keydown_kbdillumup_signal;
  keydown_eject_signal_t keydown_eject_signal;
  keydown_sleep_signal_t keydown_sleep_signal;
};
}

#endif
